### ISSUE TITLE
YAS_OAS_SPRD not working

### ISSUE THREAD

**Issue by mrBlackHat777** [leafyoung/Bloomerg_DLWS#1]
arguments

isin=AU3FN0051587 Corp

field=YAS_OAS_SPRD

Result
.000

The answer is not equals to the value in the terminal. Is there a reason?

**Comment by leafyoung** [comment]
I no longer can access a Bloomberg terminal. I can seed a few ideas: is the different value observed for every day?

**Comment by mrBlackHat777** [comment]
yes Everyday. 

All other fields are giving the correct result. I tried multiple ways to solve this problem, including overriding the pricing source but none of them were successful. 
The problem appears only in certain Isin.

There are 3 types of return in my tests (Correct value, 0 and NA)

For example, AU3FN0051587, FR0013203734, FR0013413887 returns 0.
CA31430WHQ02 returns NA.
CA31430WAB06 returns the correct value. 

Really strange problem , I sent a ticket to data license
